language: python
python:
  - "3.8"
cache: pip
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
  - coverage run tests.py
# Push the results back to codecov
after_success:
  - codecov


